---
title: "meta_analysis_term_paper_new"
author: "JIN YIYING"
date: "2022-11-27"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r data read}
list.files("meta_data_raw.csv")
meta_data_raw <- read.csv("meta_data_raw.csv", header = TRUE )
```

```{r median selection}
library("tidyverse")
library("ggplot2") 

#calculate median outcome by group_by paper_id
median_selection <- meta_data_raw %>%
  group_by(id)%>%
  summarise(
   median=median(estimate) 
    )

#merge the median outcome dataset with the raw data
median_merge <- 
  dplyr::left_join(median_selection,meta_data_raw,by = "id")

#choose data closet to the computed median outcome
median_merge$diff_squared <- (median_merge$estimate - median_merge$median)^2

#select the row of median estimates
median_dataset<- median_merge %>%
  group_by(id)%>%
  select(id, estimate,median, se,diff_squared)%>%
  slice_min(diff_squared) 

#select randomly from the row of same median_outcome within the same paper_id
median_dataset_final <- median_dataset %>%
  group_by(id)%>%
  slice_sample(n=1)%>%
  select(id,median, se)

#calculate the meta_analysis outcome
estimate_median_outcome = sum(median_dataset_final$median/median_dataset_final$se^2) / sum(1/median_dataset_final$se^2)
se_median_outcome =1/sqrt(sum(1/median_dataset_final$se^2))


#calculate the meta_analysis outcome by random effect model




#calculate the meta_analysis outcome random effect model
#install.packages("metafor")
library(metafor)
median_dataset_final_re <- median_dataset_final %>%
  mutate(variance = se^2)
m_re<- rma(yi = median_dataset_final_re$median,     # The d-column of the df, which contains Cohen's d
            vi =median_dataset_final_re$variance)    # The vi-column of the df, which contains the variances
m_re

m_fe<- rma(yi=median_dataset_final_re$median, median_dataset_final_re$variance,  method="FE", weighted=FALSE)
m_fe


#estimate_median_outcome <-0.9393
#se_median_outcome <- 0.0088
estimate_RE <- 0.9537
se_RE <- 0.0152
#estimate_RE <- 0.9909784
#se_RE <- 0.0002938


#plot median selection
ggplot(data = data.frame(x = c(0.90, 1.00)), aes(x,linetype = "Model")) +
  stat_function(fun = dnorm ,n = 1000, args = list(mean =estimate_median_outcome , sd = se_median_outcome),aes(linetype = "fixed effect model")) +
  stat_function(fun = dnorm, n = 1000, args = list(mean =estimate_RE , sd = se_RE), aes(linetype = "random effect model")) +
  scale_linetype_manual(name = "Model",
                          values =c("solid", "dashed"), 
                          labels = c("fixed effect model", "random effect model"))+
  
   theme_bw(base_size = 12) + 
    labs(
      title = "Distribution of estiamtes by median selection",
      x = "estimates",
      y = "normal distribution probability density")+
    theme(plot.title = element_text(hjust = 0.5))+
    theme(
      axis.title = element_text (size =15),
      axis.text = element_text(size = 10))+
theme(legend.position = c(0.8,0.8))

```

```{r random selection}
#the function of repeating sampling 
repeat_select_sample <- function(data,id,r){
#n is the number of random samples, r is the number of repetitions
 df = group_by(data,id)
 output <- map_dfr(1:r, ~ slice_sample(df, n=1), .id = "replicate") %>%
   dplyr::ungroup()
  return(output)
}

#random sampling 100 times
set.seed (seed=10000)
r<-1000
sampled_data <- repeat_select_sample(meta_data_raw,id,r=r)

#converge data
sampled_aggregate <- sampled_data %>%
  group_by(replicate) %>%
  summarise(
  beta_random = sum(estimate/se^2)/sum(1/se^2),
  SE_random = 1/sqrt(sum(1/se^2)),
  
  )%>%
mutate(replicate = as.numeric(replicate))%>%
arrange(replicate)

mean_variance_mixture <- sampled_aggregate %>% 
   summarize(mean = mean(beta_random),
    variance = mean(beta_random^2+SE_random^2)-(mean(beta_random))^2,
    sd = sqrt(variance))

#write.csv(x = sampled_data,file = "sampled_data.csv")
```

```{r mixutre distribution function}
#set the arrange of distribution
beta_underbar <- 0.98
beta_upperbar <- 1.01
interval <- 0.0001
beta_grid <- seq(beta_underbar,beta_upperbar,interval)
n_bin <- (beta_upperbar-beta_underbar)/interval+1

#calculate the density value of each beta_value
compute_density <- function(beta_value, sampled_aggregate){
  density_value <- sampled_aggregate %>%
   dplyr::mutate(
   density_value = dnorm(x= beta_value, mean = beta_random, sd = SE_random))
  return(density_value)
}
mixture_density_value <-
 beta_grid %>%
   map(compute_density, sampled_aggregate)

mixture_density_value_merge <- c()
for(i in 1:n_bin){
  density_value_list <-mixture_density_value[[i]]
  mixture_density_value_merge = bind_rows(mixture_density_value_merge,density_value_list)
}

#plus beta_value column on the right in order to calculate the average of specific values
beta_value <- rep(beta_grid, each=r)
mixture_density_value_merge <- bind_cols(mixture_density_value_merge, beta_value = beta_value)

#converge value as average
mixture_density_value_final <- mixture_density_value_merge %>%
  group_by(beta_value) %>%
  summarise(
  mixture_density_value = mean(density_value)
 ) 



#write.csv(x = mixture_density_value_final,file = "mixutre_density_value_final.csv")

#plot
p_random_dnorm <- ggplot(data = mixture_density_value_final, aes(beta_value,mixture_density_value))
p_random_dnorm +
  geom_line(
    size =1.5
  )+
    theme_bw(base_size = 12) + 
    labs(
      title = "Distribution of uniform selection",
      x = "estimates",
      y = "mixture distribution probability density"
      )+
    theme(plot.title = element_text(hjust = 0.5))+
    theme(
      axis.title = element_text (size =15),
      axis.text = element_text(size = 10))
print(p_random_dnorm)
```

```{r median&random}
median_density_value <- data.frame(beta_grid, density_value = dnorm(x=beta_grid, mean=estimate_median_outcome, sd=se_median_outcome))
random_density_value <- mixture_density_value_final

density1 <- median_density_value
density2 <- random_density_value

force_bind = function(df1, df2) {
    colnames(df2) = colnames(df1)
    bind_rows(df1, df2)
}
med_ran_density_value <- force_bind(density1,density2 )

selection_method <- c(rep("median selection", length(density1$beta_grid)), rep("uniform weighting selection", length(density2$beta_value)))
med_ran_density_value <- bind_cols(med_ran_density_value, selection_method=selection_method )

med_ran_value <- ggplot(med_ran_density_value, aes(beta_grid, density_value, color = selection_method,linetype = selection_method))+
  geom_line(
    size =1.5
  )+
    theme_bw(base_size = 12) + 
    labs(
      title = "Distribution of median seleciton and uniform weighting selection",
      x = "estimates",
      y = "probability density"
      )+
    theme(plot.title = element_text(hjust = 0.5))+
    theme(
      axis.title = element_text (size =15),
      axis.text = element_text(size = 10)) +
    theme(legend.position = c(0.2,0.8))
print(med_ran_value)
```

```{r KS plot}
# simulate two distributions 
#install.packages("SimMultiCorrData")
library("SimMultiCorrData") 

#r2 means number of random variables 
set.seed(seed=1000)
r2<-500

random_median_beta <- lapply(1:nrow(median_dataset_final), function(i){
  rnorm(r2, mean = median_dataset_final$median[i], sd = median_dataset_final$se[i])
})

# Create an empty dataframe and convert list to dataset
random_median_beta_df <- data.frame()
 for(i in 1:length(random_median_beta)){
  random_median_beta_df <- rbind(random_median_beta_df, random_median_beta[[i]])
 }
colnames(random_median_beta_df) <- paste0("random_estd",1:r2)

#Combine the dataset of estimates selected by median and the dataset of random median estimate 
random_median_beta_df_final <- cbind(median_dataset_final$median,median_dataset_final$se,random_median_beta_df)


#sample1 <- random_median_beta$random_beta
set.seed(seed=1000)
number_random_variables <- 500
study_number <- 29



# Calculate the standard error of each column
#data.se <-as.list(apply(random_median_beta_df, 2, function(x) sd(x) / sqrt(length(x))))
data.se <- random_median_beta_df_final$`median_dataset_final$se`

# Create a new dataset to store the effect sizes
data.cohend <- data.frame(random_estd=character(r2), SE=numeric(r2), estimate=numeric(r2), stringsAsFactors=F)
for (i in 1:r2) {
    data.cohend$random_estd[i] <- names(random_median_beta_df)[i]
    data.cohend$SE[i] <- 1/sqrt(sum(1/data.se^2))
    data.cohend$estimate[i] <-sum(random_median_beta_df_final[,i]/random_median_beta_df_final$`median_dataset_final$se`^2) / sum(1/random_median_beta_df_final$`median_dataset_final$se`^2)
}


median_original_sample <- rnorm(number_random_variables,mean=0.9941664,sd = 0.0009204)
median_random_sample_list <-mapply(rnorm,mean=data.cohend$estimate,sd = data.cohend$SE,MoreArgs = list(n=number_random_variables))

median_random_sample <-data.frame(median_random_sample_list)
colnames(median_random_sample) <-paste0("random_estd_",1:500)

for(j in 1:r2){  
  print(ks.test(median_original_sample, median_random_sample[,j]))  
}

dks <- data.frame(random_estd=character(r2), D=numeric(r2), p=numeric(r2), stringsAsFactors=F)
for(j in 1:r2){  
  k <- ks.test(median_original_sample, median_random_sample[,j])
  dks$random_estd[j] <- names(random_median_beta_df)[j]
  dks$D[j]       <- k$statistic
  dks$p[j]       <- k$p.value
}

#median vs uniform
#uniform weighting selection method
set.seed(seed=1000)
uniform_sample<-rnorm(1000,0.9945592,0.0013878)
median_sample<- rnorm(1000,0.9941664,0.0009204)
ks.test(uniform_sample,median_sample)
D_origin <-0.217

#plot
p_ks <- ggplot(data = dks,aes(x =D))+
  geom_histogram(aes(y=after_stat(density)),alpha=.2, color ="black", fill = "white",size = 0.3,bins = 15) +
  geom_density(aes(y=after_stat(density)),size = 1.5)+
  geom_vline(xintercept = D_origin, linetype = "dashed", color = "#e06666",size = 1.5)+
    annotate("text", x = D_origin, y = 5, label = "Origin", size = 4)+
 theme_bw(base_size = 12) + 
    labs(
      title = "Distribution of statistic D in K-S test",
      x = "maximum difference",
      y = "density of statistic"
      )+
    theme(plot.title = element_text(hjust = 0.5))+
    theme(
      axis.title = element_text (size =15),
      axis.text = element_text(size = 10))
print(p_ks)


```

```{r KS plot two lines}

sample1 <- median_random_sample[,4]
sample2 <- rnorm(100,0.9393,0.0088)

group <- c(rep("median", length(sample1)), rep("random", length(sample2)))
dat <- data.frame(KSD = c(sample1,sample2), group = group)
# create ECDF of data
cdf1 <- ecdf(sample1) 
cdf2 <- ecdf(sample2) 
# find min and max statistics to draw line between points of greatest distance
minMax <- seq(min(sample1, sample2), max(sample1, sample2), length.out=length(sample1)) 
x0 <- minMax[which( abs(cdf1(minMax) - cdf2(minMax)) == max(abs(cdf1(minMax) - cdf2(minMax))) )] 
y0 <- cdf1(x0) 
y1 <- cdf2(x0) 

#plot
ggplot(dat, aes(x = KSD, group = group, color = group))+
  stat_ecdf(size=1) +
    theme_bw(base_size = 10) +
    theme(legend.position ="top") +
    xlab("Sample") +
    ylab("ECDF") +
    #geom_line(size=1) +
    geom_segment(aes(x = x0[1], y = y0[1], xend = x0[1], yend = y1[1]),
        linetype = "dashed", color = "red") +
    geom_point(aes(x = x0[1] , y= y0[1]), color="red", size=5) +
    geom_point(aes(x = x0[1] , y= y1[1]), color="red", size=5) +
    ggtitle("K-S Test: Sample 1 / Sample 2") +
    theme(legend.title=element_blank())

```

```{r KS plot origin}


median_selection_estimate <- 0.9945592
median_selection_se <- 0.0013878

sample1 <- rnorm(number_random_variables,median_selection_estimate,median_selection_se)
sample2 <- rnorm(number_random_variables,uniform_weight_estimate,uniform_weight_se)

group <- c(rep("median", length(sample1)), rep("random", length(sample2)))
dat <- data.frame(KSD = c(sample1,sample2), group = group)
# create ECDF of data
cdf1 <- ecdf(sample1) 
cdf2 <- ecdf(sample2) 
# find min and max statistics to draw line between points of greatest distance
minMax <- seq(min(sample1, sample2), max(sample1, sample2), length.out=length(sample1)) 
x0 <- minMax[which( abs(cdf1(minMax) - cdf2(minMax)) == max(abs(cdf1(minMax) - cdf2(minMax))) )] 
y0 <- cdf1(x0) 
y1 <- cdf2(x0) 

#plot
ggplot(dat, aes(x = KSD, group = group, color = group))+
  stat_ecdf(size=1) +
    theme_bw(base_size = 10) +
    theme(legend.position ="top") +
    xlab("Sample") +
    ylab("ECDF") +
    #geom_line(size=1) +
    geom_segment(aes(x = x0[1], y = y0[1], xend = x0[1], yend = y1[1]),
        linetype = "dashed", color = "red") +
    geom_point(aes(x = x0[1] , y= y0[1]), color="red", size=5) +
    geom_point(aes(x = x0[1] , y= y1[1]), color="red", size=5) +
    ggtitle("K-S Test: Sample 1 / Sample 2") +
    theme(legend.title=element_blank())

```
